# Copyright (c) 2025 Eclipse Foundation.
# 
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: MIT

name: Retag Release Image as Latest

on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'The existing release tag to retag as latest'
        required: true
        default: 'v1.0.0'
      registry_name:
        description: 'Docker registry (default: ghcr.io)'
        required: false
        default: 'ghcr.io'
      image_name:
        description: 'Docker image name (default: repository name)'
        required: false

jobs:
  retag-as-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Set image name
        run: |
          if [ -z "${{ github.event.inputs.image_name }}" ]; then
            echo "IMAGE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          else
            echo "IMAGE_NAME=${{ github.event.inputs.image_name }}" >> $GITHUB_ENV
          fi

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ github.event.inputs.registry_name || 'ghcr.io' }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the existing release image
        run: |
          docker pull ${{ github.event.inputs.registry_name || 'ghcr.io' }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.source_tag }}

      - name: Tag image as latest
        run: |
          docker tag ${{ github.event.inputs.registry_name || 'ghcr.io' }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.source_tag }} ${{ github.event.inputs.registry_name || 'ghcr.io' }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Push the latest tag
        run: |
          docker push ${{ github.event.inputs.registry_name || 'ghcr.io' }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Verify pushed latest image
        run: |
          docker pull ${{ github.event.inputs.registry_name || 'ghcr.io' }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest